version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1121Revature
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  webapp:
    image: rakilzzz/ers:local # rds: rakilzzz/ers:aws
    restart: on-failure
    depends_on:
      - postgres
    deploy:
      replicas: 1
    ports:
      - '8080:8080'
volumes:
  postgres_data:
